// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DataPlatformExConfAPIMapperData string
}{
	DataPlatformExConfAPIMapperData: "data_platform_ex_conf_api_mapper_data",
}
